In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
def extract():
    df = pd.read_csv('../data/E-Commerce_data.csv')
    print('Data Extracted Successfully')
    return df

In [3]:
df = extract()

Data Extracted Successfully

In [4]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,...,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,...,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto

In [5]:
df.order_id.nunique()

99441

In [6]:
df.order_id.count()

119143

In [7]:
df.groupby('order_id')['order_id'].count().loc[lambda x : x > 1]

order_id
0008288aa423d2a3f00fcb17cd7d8719    2
00143d0f86d6fbd9f9b38ab440ac16f5    3
0016dfedd97fc2950e388d2971d718c7    2
001ab0a7578dd66cd4b0a71f5b6e1e41    3
001d8f0e34a38c37f7dba2a37d4eba8b    2
                                   ..
ffd84ab39cd5e873d8dba24342e65c01    2
ffe4b41e99d39f0b837a239110260530    2
ffecd5a79a0084f6a592288c67e3c298    3
fff8287bbae429a99bb7e8c21d151c41    2
fffb9224b6fc7c43ebb0904318b10b5f    4
Name: order_id, Length: 12947, dtype: int64

In [8]:
df.groupby('order_id')['order_item_id'].sum().unique()

array([  1.,   3.,   0.,   6.,   2.,  10.,   7.,   4.,  15.,  21.,  36.,
        12.,   5.,  20.,   9.,  11.,  28.,  30., 210.,  84.,   8.,  22.,
        78.,  55.,  91.,  40.,  14., 120.,  13.,  18., 132.,  66.,  24.,
       105.,  42., 231., 126.,  16.,  45.,  26.,  19.,  29.,  57.])

In [9]:
df.duplicated().sum()

0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   order_item_id                  118310 non-null  float64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  customer_unique_id             119143 non-null  object
 15  customer_zip_code_prefix       119143 non-null  int64
 16  customer_city                  119143 non-null  object
 17  customer_state                 119143 non-null  object
 18  review_id                      118146 non-null  object
 19  review_score                   118146 non-null  float64
 20  review_comment_title           13989 non-null   object
 21  review_comment_message         50245 non-null   object
 22  review_creation_date           118146 non-null  object
 23  review_answer_timestamp        118146 non-null  object
 24  payment_sequential             119140 non-null  float64
 25  payment_type                   119140 non-null  object
 26  payment_installments           119140 non-null  float64
 27  payment_value                  119140 non-null  float64
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  product_category_name_english  116576 non-null  object
dtypes: float64(15), int64(1), object(24)
memory usage: 36.4+ MB

In [11]:
df_null_approved = df[df['order_approved_at'].isna()]

In [12]:
df_null_approved[df_null_approved['order_status'] == 'delivered']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
6291,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaN,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17 00:00:00,1.0,0e20a07ca1714df21f9b07ca3bf7c682,...,675.0,2.0,20800.0,75.0,40.0,40.0,14882.0,jaboticabal,SP,small_appliances
19763,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaN,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21 00:00:00,1.0,2c2b6a28924791234bd386bddb17512e,...,498.0,1.0,1008.0,33.0,14.0,26.0,88090.0,florianopolis,SC,construction_tools_safety
22726,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17 00:00:00,1.0,583916a5dae918f5e89baec139141c54,...,NaN,NaN,3100.0,28.0,28.0,50.0,13360.0,capivari,SP,NaN
27089,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaN,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31 00:00:00,1.0,c6dd917a0be2a704582055949915ab32,...,1012.0,1.0,1200.0,42.0,25.0,15.0,3426.0,sao paulo,SP,cool_stuff
27688,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaN,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20 00:00:00,1.0,c6dd917a0be2a704582055949915ab32,...,1012.0,1.0,1200.0,42.0,25.0,15.0,3426.0,sao paulo,SP,cool_stuff
32107,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01 00:00:00,1.0,5ab02ca028398131a5ae91401eb49788,...,1322.0,2.0,700.0,26.0,16.0,21.0,83323.0,pinhais,PR,sports_leisure
45901,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaN,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27 00:00:00,1.0,cae2e38942c8489d9d7a87a3f525c06b,...,586.0,1.0,1700.0,33.0,8.0,23.0,14940.0,ibitinga,SP,furniture_decor
47164,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaN,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22 00:00:00,1.0,02a79d79e818ad0be36cfc843a6af7ad,...,1738.0,1.0,300.0,16.0,15.0,15.0,3028.0,sao paulo,SP,sports_leisure
57992,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaN,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16 00:00:00,1.0,c3b271f47e73d0c9ccf1b43b7606c705,...,473.0,1.0,600.0,30.0,3.0,20.0,14940.0,ibitinga,SP,furniture_decor
73778,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20 00:00:00,1.0,4fd676d9c4723d475026e40aeae56957,...,441.0,3.0,4300.0,36.0,13.0,20.0,3554.0,sao paulo,SP,garden_tools
75347,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaN,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29 00:00:00,1.0,7868a64aa111bbb4f41f8e1146c0becb,...,438.0,1.0,1200.0,30.0,5.0,20.0,14940.0,ibitinga,SP,furniture_decor
80965,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21 00:00:00,1.0,8c5876b1c7768217964f353bc7e64393,...,440.0,1.0,250.0,18.0,3.0,28.0,11010.0,santos,SP,telephony
80966,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21 00:00:00,2.0,8c5876b1c7768217964f353bc7e64393,...,440.0,1.0,250.0,18.0,3.0,28.0,11010.0,santos,SP,telephony
86631,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaN,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23 00:00:00,1.0,db8ed3d08891d16a2438a67ab3acb740,...,702.0,1.0,2700.0,42.0,11.0,36.0,14940.0,ibitinga,SP,bed_bath_table
101691,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaN,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31 00:00:00,1.0,c6dd917a0be2a704582055949915ab32,...,1012.0,1.0,1200.0,42.0,25.0,15.0,3426.0,sao paulo,SP,cool_stuff

In [13]:
df['price'] = df['price'].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   order_item_id                  118310 non-null  float64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          119143 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  customer_unique_id             119143 non-null  object
 15  customer_zip_code_prefix       119143 non-null  int64
 16  customer_city                  119143 non-null  object
 17  customer_state                 119143 non-null  object
 18  review_id                      118146 non-null  object
 19  review_score                   118146 non-null  float64
 20  review_comment_title           13989 non-null   object
 21  review_comment_message         50245 non-null   object
 22  review_creation_date           118146 non-null  object
 23  review_answer_timestamp        118146 non-null  object
 24  payment_sequential             119140 non-null  float64
 25  payment_type                   119140 non-null  object
 26  payment_installments           119140 non-null  float64
 27  payment_value                  119140 non-null  float64
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  product_category_name_english  116576 non-null  object
dtypes: float64(15), int64(1), object(24)
memory usage: 36.4+ MB

In [14]:
df3 = df[df['order_item_id'].isna() & df['seller_id'].isna() & df['product_id'].isna()].dropna(inplace=True)

C:\Users\khali\AppData\Local\Temp\ipykernel_16472\4231362525.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3 = df[df['order_item_id'].isna() & df['seller_id'].isna() & df['product_id'].isna()].dropna(inplace=True)

In [15]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,...,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,...,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,828.0,4.0,4950.0,40.0,10.0,40.0,17602.0,tupa,SP,baby
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,b80910977a37536adeddd63663f916ad,...,500.0,2.0,13300.0,32.0,90.0,22.0,8290.0,sao paulo,SP,home_appliances_2
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG,computers_accessories
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG,computers_accessories
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,569.0,1.0,150.0,16.0,7.0,15.0,14407.0,franca,SP,health_beauty

In [16]:
df[df['order_item_id'].isna() & df['seller_id'].isna() & df['product_id'].isna()].order_status.unique()

array(['unavailable', 'canceled', 'created', 'shipped', 'invoiced'],
      dtype=object)

In [17]:
df.dropna(inplace=True, subset='product_id')
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,...,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,...,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,828.0,4.0,4950.0,40.0,10.0,40.0,17602.0,tupa,SP,baby
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,1.0,b80910977a37536adeddd63663f916ad,...,500.0,2.0,13300.0,32.0,90.0,22.0,8290.0,sao paulo,SP,home_appliances_2
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG,computers_accessories
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,...,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG,computers_accessories
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,569.0,1.0,150.0,16.0,7.0,15.0,14407.0,franca,SP,health_beauty

In [18]:
df.groupby('order_status').order_status.count()

order_status
approved            3
canceled          570
delivered      115723
invoiced          376
processing        376
shipped          1255
unavailable         7
Name: order_status, dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118310 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  object
 4   order_approved_at              118295 non-null  object
 5   order_delivered_carrier_date   117056 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  118310 non-null  object
 8   order_item_id                  118310 non-null  float64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  customer_unique_id             118310 non-null  object
 15  customer_zip_code_prefix       118310 non-null  int64
 16  customer_city                  118310 non-null  object
 17  customer_state                 118310 non-null  object
 18  review_id                      117332 non-null  object
 19  review_score                   117332 non-null  float64
 20  review_comment_title           13892 non-null   object
 21  review_comment_message         49682 non-null   object
 22  review_creation_date           117332 non-null  object
 23  review_answer_timestamp        117332 non-null  object
 24  payment_sequential             118307 non-null  float64
 25  payment_type                   118307 non-null  object
 26  payment_installments           118307 non-null  float64
 27  payment_value                  118307 non-null  float64
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  product_category_name_english  116576 non-null  object
dtypes: float64(15), int64(1), object(24)
memory usage: 37.0+ MB

In [20]:
df['product_category_name_english'].unique().__len__() - df['product_category_name'].unique().__len__()

-2

In [21]:
df['product_category_name_english'].unique()

array(['housewares', 'perfumery', 'auto', 'pet_shop', 'stationery', nan,
       'furniture_decor', 'office_furniture', 'garden_tools',
       'computers_accessories', 'bed_bath_table', 'toys',
       'construction_tools_construction', 'telephony', 'health_beauty',
       'electronics', 'baby', 'cool_stuff', 'watches_gifts',
       'air_conditioning', 'sports_leisure', 'books_general_interest',
       'small_appliances', 'food', 'luggage_accessories',
       'fashion_underwear_beach', 'christmas_supplies',
       'fashion_bags_accessories', 'musical_instruments',
       'construction_tools_lights', 'books_technical',
       'costruction_tools_garden', 'home_appliances', 'market_place',
       'agro_industry_and_commerce', 'party_supplies', 'home_confort',
       'cds_dvds_musicals', 'industry_commerce_and_business',
       'consoles_games', 'furniture_bedroom', 'construction_tools_safety',
       'fixed_telephony', 'drinks',
       'kitchen_dining_laundry_garden_furniture', 'fashion_shoes',
       'home_construction', 'audio', 'home_appliances_2',
       'fashion_male_clothing', 'cine_photo', 'furniture_living_room',
       'art', 'food_drink', 'tablets_printing_image', 'fashion_sport',
       'la_cuisine', 'flowers', 'computers', 'home_comfort_2',
       'small_appliances_home_oven_and_coffee', 'dvds_blu_ray',
       'costruction_tools_tools', 'fashio_female_clothing',
       'furniture_mattress_and_upholstery', 'signaling_and_security',
       'diapers_and_hygiene', 'books_imported',
       'fashion_childrens_clothes', 'music', 'arts_and_craftmanship',
       'security_and_services'], dtype=object)

In [22]:
df['product_category_name'].unique()

array(['utilidades_domesticas', 'perfumaria', 'automotivo', 'pet_shop',
       'papelaria', nan, 'moveis_decoracao', 'moveis_escritorio',
       'ferramentas_jardim', 'informatica_acessorios', 'cama_mesa_banho',
       'brinquedos', 'construcao_ferramentas_construcao', 'telefonia',
       'beleza_saude', 'eletronicos', 'bebes', 'cool_stuff',
       'relogios_presentes', 'climatizacao', 'esporte_lazer',
       'livros_interesse_geral', 'eletroportateis', 'alimentos',
       'malas_acessorios', 'fashion_underwear_e_moda_praia',
       'artigos_de_natal', 'fashion_bolsas_e_acessorios',
       'instrumentos_musicais', 'construcao_ferramentas_iluminacao',
       'livros_tecnicos', 'construcao_ferramentas_jardim',
       'eletrodomesticos', 'market_place', 'agro_industria_e_comercio',
       'artigos_de_festas', 'casa_conforto', 'cds_dvds_musicais',
       'industria_comercio_e_negocios', 'consoles_games', 'moveis_quarto',
       'construcao_ferramentas_seguranca', 'telefonia_fixa', 'bebidas',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'fashion_calcados', 'casa_construcao', 'audio',
       'eletrodomesticos_2', 'fashion_roupa_masculina', 'cine_foto',
       'moveis_sala', 'artes', 'alimentos_bebidas',
       'tablets_impressao_imagem', 'fashion_esporte',
       'portateis_cozinha_e_preparadores_de_alimentos', 'la_cuisine',
       'flores', 'pcs', 'casa_conforto_2', 'portateis_casa_forno_e_cafe',
       'dvds_blu_ray', 'pc_gamer', 'construcao_ferramentas_ferramentas',
       'fashion_roupa_feminina', 'moveis_colchao_e_estofado',
       'sinalizacao_e_seguranca', 'fraldas_higiene', 'livros_importados',
       'fashion_roupa_infanto_juvenil', 'musica', 'artes_e_artesanato',
       'seguros_e_servicos'], dtype=object)

In [23]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,...,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,...,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto

In [24]:
df[df['payment_type'].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
36864,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,1.0,5a6b04657a4c5ee34285d1e4619a96b4,...,1036.0,1.0,1000.0,16.0,16.0,16.0,81810.0,curitiba,PR,health_beauty
36865,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,2.0,5a6b04657a4c5ee34285d1e4619a96b4,...,1036.0,1.0,1000.0,16.0,16.0,16.0,81810.0,curitiba,PR,health_beauty
36866,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00,3.0,5a6b04657a4c5ee34285d1e4619a96b4,...,1036.0,1.0,1000.0,16.0,16.0,16.0,81810.0,curitiba,PR,health_beauty

In [25]:
df['payment_type'].unique()

array(['credit_card', 'voucher', 'boleto', 'debit_card', nan],
      dtype=object)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118310 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  object
 4   order_approved_at              118295 non-null  object
 5   order_delivered_carrier_date   117056 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  118310 non-null  object
 8   order_item_id                  118310 non-null  float64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  customer_unique_id             118310 non-null  object
 15  customer_zip_code_prefix       118310 non-null  int64
 16  customer_city                  118310 non-null  object
 17  customer_state                 118310 non-null  object
 18  review_id                      117332 non-null  object
 19  review_score                   117332 non-null  float64
 20  review_comment_title           13892 non-null   object
 21  review_comment_message         49682 non-null   object
 22  review_creation_date           117332 non-null  object
 23  review_answer_timestamp        117332 non-null  object
 24  payment_sequential             118307 non-null  float64
 25  payment_type                   118307 non-null  object
 26  payment_installments           118307 non-null  float64
 27  payment_value                  118307 non-null  float64
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  product_category_name_english  116576 non-null  object
dtypes: float64(15), int64(1), object(24)
memory usage: 37.0+ MB

In [27]:
df_customers = pd.read_csv('../data/full data/customers_dataset.csv')

In [28]:
df_customers['customer_unique_id'].unique().__len__()

96096

In [29]:
df_customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [30]:
df_customers[['customer_unique_id','customer_zip_code_prefix', 'customer_city', 'customer_state']]

,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...
99436,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [31]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'seller_zip_code_prefix',
       'seller_city', 'seller_state', 'product_category_name_english'],
      dtype='object')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118310 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118310 non-null  object
 1   customer_id                    118310 non-null  object
 2   order_status                   118310 non-null  object
 3   order_purchase_timestamp       118310 non-null  object
 4   order_approved_at              118295 non-null  object
 5   order_delivered_carrier_date   117056 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  118310 non-null  object
 8   order_item_id                  118310 non-null  float64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  customer_unique_id             118310 non-null  object
 15  customer_zip_code_prefix       118310 non-null  int64
 16  customer_city                  118310 non-null  object
 17  customer_state                 118310 non-null  object
 18  review_id                      117332 non-null  object
 19  review_score                   117332 non-null  float64
 20  review_comment_title           13892 non-null   object
 21  review_comment_message         49682 non-null   object
 22  review_creation_date           117332 non-null  object
 23  review_answer_timestamp        117332 non-null  object
 24  payment_sequential             118307 non-null  float64
 25  payment_type                   118307 non-null  object
 26  payment_installments           118307 non-null  float64
 27  payment_value                  118307 non-null  float64
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  product_category_name_english  116576 non-null  object
dtypes: float64(15), int64(1), object(24)
memory usage: 37.0+ MB

In [33]:
df.customer_unique_id.nunique()

95420

In [34]:
SERVER = 'localhost'
DATABASE = 'E-Commerce'
DRIVER = 'ODBC Driver 17 for SQL Server'
connection_string = f'mssql+pyodbc://@{SERVER}/{DATABASE}?trusted_connection=yes&driver={DRIVER}'
engine = create_engine(connection_string)

In [35]:
def to_date_key(dt_series):
    return pd.to_datetime(dt_series).dt.strftime('%Y%m%d').fillna(-1).astype(int)

In [36]:
date_cols = [
    'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date',
    'order_delivered_customer_date', 'order_estimated_delivery_date', 
    'review_creation_date', 'review_answer_timestamp', 'shipping_limit_date'
]

all_dates = pd.concat([df[col] for col in date_cols]).dropna().unique()
date_range = pd.date_range(start=pd.to_datetime(min(all_dates)), end=pd.to_datetime(max(all_dates)))

dim_date = pd.DataFrame({
    'DateKey': [int(d.strftime('%Y%m%d')) for d in date_range],
    'FullDate': date_range,
    'DayNumberOfWeek': date_range.dayofweek + 1,
    'DayNameOfWeek': date_range.day_name(),
    'DayNumberOfMonth': date_range.day,
    'MonthNumberOfYear': date_range.month,
    'MonthName': date_range.month_name(),
    'Quarter': date_range.quarter,
    'Year': date_range.year,
    'IsWeekend': (date_range.dayofweek >= 5).astype(int)
})

# Add missing date placeholder (-1)
missing_date = pd.DataFrame([[-1, pd.to_datetime('1900-01-01'), 0, 'N/A', 0, 0, 'N/A', 0, 0, 0]], columns=dim_date.columns)
dim_date = pd.concat([missing_date, dim_date]).drop_duplicates(subset=['DateKey'])
dim_date.to_sql('dim_date', engine, if_exists='append', index=False)

61

In [37]:
dim_date

,DateKey,FullDate,DayNumberOfWeek,DayNameOfWeek,DayNumberOfMonth,MonthNumberOfYear,MonthName,Quarter,Year,IsWeekend
0,-1,1900-01-01 00:00:00,0,N/A,0,0,N/A,0,0,0
0,20160904,2016-09-04 21:15:19,7,Sunday,4,9,September,3,2016,1
1,20160905,2016-09-05 21:15:19,1,Monday,5,9,September,3,2016,0
2,20160906,2016-09-06 21:15:19,2,Tuesday,6,9,September,3,2016,0
3,20160907,2016-09-07 21:15:19,3,Wednesday,7,9,September,3,2016,0
...,...,...,...,...,...,...,...,...,...,...
1309,20200405,2020-04-05 21:15:19,7,Sunday,5,4,April,2,2020,1
1310,20200406,2020-04-06 21:15:19,1,Monday,6,4,April,2,2020,0
1311,20200407,2020-04-07 21:15:19,2,Tuesday,7,4,April,2,2020,0
1312,20200408,2020-04-08 21:15:19,3,Wednesday,8,4,April,2,2020,0
1313,20200409,2020-04-09 21:15:19,4,Thursday,9,4,April,2,2020,0

In [38]:
customers = df[['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']].drop_duplicates(subset=['customer_id'])
customers.to_sql('dim_customers', engine, if_exists='append', index=False)

201

In [39]:
products = df[['product_id', 'product_category_name', 'product_category_name_english', 
               'product_name_lenght', 'product_description_lenght', 'product_photos_qty',
               'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']].drop_duplicates(subset=['product_id'])
products.to_sql('dim_products', engine, if_exists='append', index=False)

138

In [40]:
sellers = df[['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']].drop_duplicates(subset=['seller_id'])
sellers.to_sql('dim_sellers', engine, if_exists='append', index=False)

475

In [41]:
reviews = df[['review_id', 'review_score', 'review_comment_title', 'review_comment_message', 
              'review_creation_date', 'review_answer_timestamp']].drop_duplicates(subset=['review_id'])
reviews['review_creation_date_key'] = to_date_key(reviews['review_creation_date'])
reviews['review_answer_timestamp'] = pd.to_datetime(reviews['review_answer_timestamp'])
reviews.drop(columns=['review_creation_date']).to_sql('dim_reviews', engine, if_exists='append', index=False)

339

In [42]:
dim_cust_lookup = pd.read_sql('SELECT customer_id, CustomerKey FROM dim_customers', engine)
dim_prod_lookup = pd.read_sql('SELECT product_id, ProductKey FROM dim_products', engine)
dim_sell_lookup = pd.read_sql('SELECT seller_id, SellerKey FROM dim_sellers', engine)
dim_rev_lookup  = pd.read_sql('SELECT review_id, ReviewKey FROM dim_reviews', engine)

In [43]:
fact = df.copy()
fact = fact.merge(dim_cust_lookup, on='customer_id', how='left')
fact = fact.merge(dim_prod_lookup, on='product_id', how='left')
fact = fact.merge(dim_sell_lookup, on='seller_id', how='left')
fact = fact.merge(dim_rev_lookup, on='review_id', how='left')

In [44]:
fact['OrderPurchaseDateKey']    = to_date_key(fact['order_purchase_timestamp'])
fact['OrderApprovedDateKey']    = to_date_key(fact['order_approved_at'])
fact['DeliveredCarrierDateKey'] = to_date_key(fact['order_delivered_carrier_date'])
fact['DeliveredCustomerDateKey'] = to_date_key(fact['order_delivered_customer_date'])
fact['EstimatedDeliveryDateKey'] = to_date_key(fact['order_estimated_delivery_date'])
fact['ReviewCreationDateKey']   = to_date_key(fact['review_creation_date'])
fact['ReviewAnswerDateKey']     = to_date_key(fact['review_answer_timestamp'])
fact['ShippingLimitDateKey']    = to_date_key(fact['shipping_limit_date'])

# Final selection for the Fact Table
fact_orders = fact[[
    'order_id', 'order_item_id', 'order_status', 'CustomerKey', 'ProductKey', 'SellerKey', 'ReviewKey',
    'price', 'freight_value', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value',
    'OrderPurchaseDateKey', 'OrderApprovedDateKey', 'DeliveredCarrierDateKey',
    'DeliveredCustomerDateKey', 'EstimatedDeliveryDateKey', 'ReviewCreationDateKey',
    'ReviewAnswerDateKey', 'ShippingLimitDateKey'
]]

fact_orders.to_sql('fact_orders', engine, if_exists='append', index=False, chunksize=1000)
print("ETL Completed Successfully!")

ETL Completed Successfully!